[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
googlemaps = "^4.10.0"
schedule = "^1.2.2"
fastlite = "^0.0.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
